"""message seq

Revision ID: 3567216eaea7
Revises: 068bcd675a71
Create Date: 2026-07-16 04:22:08.124555

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3567216eaea7'
down_revision: str | None = '068bcd675a71'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_unique_constraint(None, 'messages', ['seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_column('messages', 'seq')
    # ### end Alembic commands ###
